sudo: required
language: node_js
node_js:
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - libfontconfig1
      - libstdc++6
      - lsb-base
      - google-chrome-stable
before_instal:
  - sudo apt-get update
  - sudo apt-get libfontconfig1 -y