sudo: required
dist: trusty
language: node_js
node_js:
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script: cross-env NODE_ENV=test node_modules/karma/bin/karma start --single-run --no-auto-watch config/karma.conf.js
before_install:
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-linux-ubuntu-trusty-x86_64.tar.gz
  - tar -zxvf phantomjs-2.5.0-beta-linux-ubuntu-trusty-x86_64.tar.gz
  - mv phantomjs-2.5.0-beta-ubuntu-trusty phantomjs
  - chmod +x phantomjs/bin/phantomjs
  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
  - sudo mv phantomjs /usr/local/phantomjs/bin
  - phantomjs -v
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3