sudo: required
dist: trusty
language: node_js
node_js:
addons:
  firefox: "latest"
  apt:
    packages:
      - google-chrome-stable
script: node_modules/karma/bin/karma start --single-run --no-auto-watch config/karma.conf.js
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3